services:
  receiver:
    build: ./receiver
    ports:
      - 8000:8000
    volumes:
      - ./receiver/data.json:/app/data.json
  scanner1:
    build: ./scanner
    environment:
      - RECEIVER_URL=http://receiver:8000/report
  scanner2:
    build: ./scanner
    environment:
      - RECEIVER_URL=http://receiver:8000/report
