services:
  receiver:
    build: ./receiver
    ports:
      - 8000:8000
    # volumes:
    #   - myVolume

  scanner1:
    build: ./scanner
    ports:
      - 8001:8001
    environment:
      - RECEIVER_URL=http://receiver:8000/report
  scanner2:
    build: ./scanner
    ports:
      - 8002:8002
    environment:
      - RECEIVER_URL=http://receiver:8000/reports
volumes:
  myVolume:
    external: true
