services:
  receiver:
    build: ./receiver
    ports:
      - "8000:8000"
    volumes:
      - ./receiver/data.json:/app/data.json
  scanner1:
    build: ./scanner
    env_file:
      - /receiver/.env
  scanner2:
    build: ./scanner
    env_file:
      - ./receiver/.env
